version: '3'

services:
  adunaphel:
    image: zerpex/deb_lxde_x2go
    container_name: desktop_debian-lxde-x2go
    volumes:
      - ./files/home:/home
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - TIME_ZONE=Europe/Paris            # Default to Europe/Paris
      - LANGUAGE=fr_FR                    # Default to fr_FR  
      - CODEPAGE=UTF8                     # Default to UTF8
      - USER=logan                        # Default user "logan"
      - USER_PASS=                        # Will be generated randomly if not set
      - ROOT_PASS=                        # Will be generated randomly if not set
    ports:
      - "18000:22"

volumes:
  files:
    driver: local
