version: '3'

services:
  adunaphel:
    image: zerpex/deb_lxde_x2go
    container_name: client-adunaphel_debian
    hostname: adunaphel
    domainname: jayjay.pm
    volumes:
      - ./files/adunaphel_home:/home
      - /mnt/incoming:/mnt/incoming
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - TIME_ZONE=Europe/Paris
      - LANG=fr_FR
      - CODEPAGE=UTF8
      - ROOT_PASS=
    ports:
      - 6080:22

volumes:
  files:
    driver: local
